/**
 * Maps cropCode to a plant icon image path under /assets/images/plant-icons/.
 * cropCode is generated by seed.ts: uppercase, remove diacritics, spaces → underscore.
 * Falls back to lua.png for any unmapped crop.
 */

const FALLBACK = "/assets/images/plant-icons/lua.png";

// Keys match the cropCode generated by seed.ts from the crop name list
const CROP_ICON_MAP: Record<string, string> = {
  // Lúa (01–03)
  RICE:     "/assets/images/plant-icons/lua.png",
  CAY_LUA_95100:     "/assets/images/plant-icons/lua.png",
  CAY_LUA_NHAT_DS1:   "/assets/images/plant-icons/lua-nhat-ds1.png",
  CAY_LUA_NEP:        "/assets/images/plant-icons/lua-nep.png",
  // Cà phê (04)
  COFFEE:         "/assets/images/plant-icons/ca-phe.png",
  // Sầu riêng (05–06)
  DURIAN:      "/assets/images/plant-icons/sau-rieng.png",
  CAY_SAU_RIENG_TO:   "/assets/images/plant-icons/sau-rieng-to.png",
  // Xoài (07–08)
  MANGO:           "/assets/images/plant-icons/xoai.png",
  CAY_XOAI_L:        "/assets/images/plant-icons/xoai-dl.png",
  // Rau (09–11)
  CAY_RAU_AN_LA:      "/assets/images/plant-icons/rau-an-la.png",
  CAY_RAU_AN_CU:      "/assets/images/plant-icons/rau-an-cu.png",
  CAY_RAU_AN_TRAI:    "/assets/images/plant-icons/rau-an-trai.png",
  BAU_BI_DUA:    "/assets/images/plant-icons/rau-an-trai.png",
  // Cà chua (12) — không có file riêng, dùng rau-an-trai
  CAY_CA_CHUA:        "/assets/images/plant-icons/rau-an-trai.png",
  // Dưa hấu (13)
  CAY_DUA_HAU:        "/assets/images/plant-icons/dua-hau.png",
  // Hoa cúc (14)
  CAY_HOA_CUC:        "/assets/images/plant-icons/hoa-cuc.png",
  // Các cây không số thứ tự
  CAY_BAP_CAI:        "/assets/images/plant-icons/bap-cai.png",
  CAY_CAM:            "/assets/images/plant-icons/cam.png",
  CAY_CHANH:          "/assets/images/plant-icons/chanh.png",
  CAY_CHUOI:          "/assets/images/plant-icons/chuoi.png",
  CAY_CO_MUI:         "/assets/images/plant-icons/co-mui.png",
  CAY_AU:            "/assets/images/plant-icons/dau.png",
  CAY_DAU_TAY:        "/assets/images/plant-icons/dau-tay.png",
  CAY_IEU:           "/assets/images/plant-icons/dieu.png",
  CAY_DUA:            "/assets/images/plant-icons/dua.png",
  CAY_HANH:           "/assets/images/plant-icons/hanh.png",
  PEPPER:        "/assets/images/plant-icons/ho-tieu.png",
  CAY_KHOAI_TAY:      "/assets/images/plant-icons/khoai-tay.png",
  CAY_MAN:            "/assets/images/plant-icons/man.png",
  CAY_OT:             "/assets/images/plant-icons/ot.png",
  CAY_TAO:            "/assets/images/plant-icons/tao.png",
  CAY_THANH_LONG:     "/assets/images/plant-icons/thanh-long.png",
  CAY_VAI:            "/assets/images/plant-icons/vai.png",
};

export function getCropImagePath(cropCode: string): string {
  if (CROP_ICON_MAP[cropCode]) return CROP_ICON_MAP[cropCode];

  // Fuzzy: check if any key is a substring of cropCode or vice versa
  for (const [key, path] of Object.entries(CROP_ICON_MAP)) {
    if (cropCode.includes(key) || key.includes(cropCode)) return path;
  }

  return FALLBACK;
}
