/**
 * Maps cropCode or cropName to a plant icon image path under /assets/images/plant-icons/.
 * Falls back to lua.png for any unmapped crop.
 */

const FALLBACK = "/assets/images/plant-icons/lua.png";

export function normalizeCropText(str?: string | null): string {
  if (!str) return "";
  return str
    .toUpperCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/Đ/g, "D")
    .replace(/[^A-Z0-9]/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_|_$/g, "");
}

// Keys match the cropCode generated by seed.ts from the crop name list + aliases
const CROP_ICON_MAP: Record<string, string> = {
  // Lúa (01–03)
  RICE: "/assets/images/plant-icons/lua.png",
  LUA: "/assets/images/plant-icons/lua.png",
  CAY_LUA: "/assets/images/plant-icons/lua.png",
  CAY_LUA_95100: "/assets/images/plant-icons/lua.png",
  CAY_LUA_NHAT_DS1: "/assets/images/plant-icons/lua-nhat-ds1.png",
  CAY_LUA_NEP: "/assets/images/plant-icons/lua-nep.png",

  // Cà phê (04)
  COFFEE: "/assets/images/plant-icons/ca-phe.png",
  CA_PHE: "/assets/images/plant-icons/ca-phe.png",
  CAY_CA_PHE: "/assets/images/plant-icons/ca-phe.png",

  // Sầu riêng (05–06)
  DURIAN: "/assets/images/plant-icons/sau-rieng.png",
  SAU_RIENG: "/assets/images/plant-icons/sau-rieng.png",
  CAY_SAU_RIENG: "/assets/images/plant-icons/sau-rieng.png",
  CAY_SAU_RIENG_TO: "/assets/images/plant-icons/sau-rieng-to.png",

  // Xoài (07–08)
  MANGO: "/assets/images/plant-icons/xoai.png",
  XOAI: "/assets/images/plant-icons/xoai.png",
  CAY_XOAI: "/assets/images/plant-icons/xoai.png",
  CAY_XOAI_L: "/assets/images/plant-icons/xoai-dl.png",
  CAY_XOAI_DL: "/assets/images/plant-icons/xoai-dl.png",

  // Rau (09–11)
  CAY_RAU_AN_LA: "/assets/images/plant-icons/rau-an-la.png",
  RAU_AN_LA: "/assets/images/plant-icons/rau-an-la.png",
  CAY_RAU_AN_CU: "/assets/images/plant-icons/rau-an-cu.png",
  RAU_AN_CU: "/assets/images/plant-icons/rau-an-cu.png",
  CAY_RAU_AN_TRAI: "/assets/images/plant-icons/rau-an-trai.png",
  RAU_AN_TRAI: "/assets/images/plant-icons/rau-an-trai.png",
  BAU_BI_DUA: "/assets/images/plant-icons/rau-an-trai.png",

  // Cải xanh -> rau-an-la
  CAI_XANH: "/assets/images/plant-icons/rau-an-la.png",
  CAY_CAI_XANH: "/assets/images/plant-icons/rau-an-la.png",
  RAU_CAI_XANH: "/assets/images/plant-icons/rau-an-la.png",
  CAI: "/assets/images/plant-icons/rau-an-la.png",

  // Xà lách / Salad
  XA_LACH: "/assets/images/plant-icons/xa-lach.png",
  CAY_XA_LACH: "/assets/images/plant-icons/xa-lach.png",
  RAU_XA_LACH: "/assets/images/plant-icons/xa-lach.png",
  SA_LACH: "/assets/images/plant-icons/xa-lach.png",
  CAY_SA_LACH: "/assets/images/plant-icons/xa-lach.png",
  SALAD: "/assets/images/plant-icons/xa-lach.png",
  CAY_SALAD: "/assets/images/plant-icons/xa-lach.png",
  LETTUCE: "/assets/images/plant-icons/xa-lach.png",

  // Bắp (ngô)
  BAP: "/assets/images/plant-icons/bap.png",
  CAY_BAP: "/assets/images/plant-icons/bap.png",
  NGO: "/assets/images/plant-icons/bap.png",
  CAY_NGO: "/assets/images/plant-icons/bap.png",
  CORN: "/assets/images/plant-icons/bap.png",

  // Cà chua (12)
  CAY_CA_CHUA: "/assets/images/plant-icons/ca-chua.png",
  CA_CHUA: "/assets/images/plant-icons/ca-chua.png",
  TOMATO: "/assets/images/plant-icons/ca-chua.png",

  // Dưa hấu (13)
  CAY_DUA_HAU: "/assets/images/plant-icons/dua-hau.png",
  DUA_HAU: "/assets/images/plant-icons/dua-hau.png",
  WATERMELON: "/assets/images/plant-icons/dua-hau.png",

  // Hoa cúc (14)
  CAY_HOA_CUC: "/assets/images/plant-icons/hoa-cuc.png",
  HOA_CUC: "/assets/images/plant-icons/hoa-cuc.png",

  // Bắp cải (cabbage) -> bap-cai.png
  CAY_BAP_CAI: "/assets/images/plant-icons/bap-cai.png",
  BAP_CAI: "/assets/images/plant-icons/bap-cai.png",
  CABBAGE: "/assets/images/plant-icons/bap-cai.png",

  CAY_CAM: "/assets/images/plant-icons/cam.png",
  CAM: "/assets/images/plant-icons/cam.png",
  ORANGE: "/assets/images/plant-icons/cam.png",

  CAY_CHANH: "/assets/images/plant-icons/chanh.png",
  CHANH: "/assets/images/plant-icons/chanh.png",
  LEMON: "/assets/images/plant-icons/chanh.png",
  LIME: "/assets/images/plant-icons/chanh.png",

  CAY_CHUOI: "/assets/images/plant-icons/chuoi.png",
  CHUOI: "/assets/images/plant-icons/chuoi.png",
  BANANA: "/assets/images/plant-icons/chuoi.png",

  CAY_CO_MUI: "/assets/images/plant-icons/co-mui.png",
  CO_MUI: "/assets/images/plant-icons/co-mui.png",

  // Đậu / Đậu phộng / Đậu phông -> dau.png
  CAY_AU: "/assets/images/plant-icons/dau.png",
  CAY_DAU: "/assets/images/plant-icons/dau.png",
  DAU: "/assets/images/plant-icons/dau.png",
  DAU_PHONG: "/assets/images/plant-icons/dau.png",
  CAY_DAU_PHONG: "/assets/images/plant-icons/dau.png",
  AU_PHONG: "/assets/images/plant-icons/dau.png",
  CAY_AU_PHONG: "/assets/images/plant-icons/dau.png",
  PEANUT: "/assets/images/plant-icons/dau.png",
  LAC: "/assets/images/plant-icons/dau.png",
  CAY_LAC: "/assets/images/plant-icons/dau.png",

  CAY_DAU_TAY: "/assets/images/plant-icons/dau-tay.png",
  DAU_TAY: "/assets/images/plant-icons/dau-tay.png",
  STRAWBERRY: "/assets/images/plant-icons/dau-tay.png",

  CAY_IEU: "/assets/images/plant-icons/dieu.png",
  CAY_DIEU: "/assets/images/plant-icons/dieu.png",
  DIEU: "/assets/images/plant-icons/dieu.png",
  CASHEW: "/assets/images/plant-icons/dieu.png",

  CAY_DUA: "/assets/images/plant-icons/dua.png",
  DUA: "/assets/images/plant-icons/dua.png",
  PINEAPPLE: "/assets/images/plant-icons/dua.png",

  CAY_HANH: "/assets/images/plant-icons/hanh.png",
  HANH: "/assets/images/plant-icons/hanh.png",
  ONION: "/assets/images/plant-icons/hanh.png",

  // Tiêu / Hồ tiêu -> ho-tieu.png
  PEPPER: "/assets/images/plant-icons/ho-tieu.png",
  TIEU: "/assets/images/plant-icons/ho-tieu.png",
  CAY_TIEU: "/assets/images/plant-icons/ho-tieu.png",
  HO_TIEU: "/assets/images/plant-icons/ho-tieu.png",
  CAY_HO_TIEU: "/assets/images/plant-icons/ho-tieu.png",

  CAY_KHOAI_TAY: "/assets/images/plant-icons/khoai-tay.png",
  KHOAI_TAY: "/assets/images/plant-icons/khoai-tay.png",
  POTATO: "/assets/images/plant-icons/khoai-tay.png",

  CAY_MAN: "/assets/images/plant-icons/man.png",
  MAN: "/assets/images/plant-icons/man.png",
  PLUM: "/assets/images/plant-icons/man.png",

  // Nhãn -> nhan.png
  NHAN: "/assets/images/plant-icons/nhan.png",
  CAY_NHAN: "/assets/images/plant-icons/nhan.png",
  LONGAN: "/assets/images/plant-icons/nhan.png",

  // Nho -> nho.png
  NHO: "/assets/images/plant-icons/nho.png",
  CAY_NHO: "/assets/images/plant-icons/nho.png",
  GRAPE: "/assets/images/plant-icons/nho.png",

  CAY_OT: "/assets/images/plant-icons/ot.png",
  OT: "/assets/images/plant-icons/ot.png",
  CHILI: "/assets/images/plant-icons/ot.png",

  // Quýt -> quyt.png
  QUYT: "/assets/images/plant-icons/quyt.png",
  CAY_QUYT: "/assets/images/plant-icons/quyt.png",
  MANDARIN: "/assets/images/plant-icons/quyt.png",

  // Lê -> le.png
  LE: "/assets/images/plant-icons/le.png",
  CAY_LE: "/assets/images/plant-icons/le.png",
  PEAR: "/assets/images/plant-icons/le.png",

  CAY_TAO: "/assets/images/plant-icons/tao.png",
  TAO: "/assets/images/plant-icons/tao.png",
  APPLE: "/assets/images/plant-icons/tao.png",

  CAY_THANH_LONG: "/assets/images/plant-icons/thanh-long.png",
  THANH_LONG: "/assets/images/plant-icons/thanh-long.png",
  DRAGON_FRUIT: "/assets/images/plant-icons/thanh-long.png",

  CAY_VAI: "/assets/images/plant-icons/vai.png",
  VAI: "/assets/images/plant-icons/vai.png",
  LYCHEE: "/assets/images/plant-icons/vai.png",

  TRAU_BA: "/assets/images/plant-icons/trau-ba.png",
  CAY_TRAU_BA: "/assets/images/plant-icons/trau-ba.png",

  KIM_NGAN: "/assets/images/plant-icons/kim-ngan.png",
  CAY_KIM_NGAN: "/assets/images/plant-icons/kim-ngan.png",

  LAN: "/assets/images/plant-icons/lan.png",
  CAY_LAN: "/assets/images/plant-icons/lan.png",

  PHAT_TAI: "/assets/images/plant-icons/phat-tai.png",
  CAY_PHAT_TAI: "/assets/images/plant-icons/phat-tai.png",

  RAU_MA: "/assets/images/plant-icons/rau-ma.png",
  CAY_RAU_MA: "/assets/images/plant-icons/rau-ma.png",

  MAI: "/assets/images/plant-icons/mai.png",
  CAY_MAI: "/assets/images/plant-icons/mai.png",
};

export function getCropImagePath(cropCode?: string | null, cropName?: string | null): string {
  const rawCode = (cropCode || "").trim();
  const rawName = (cropName || "").trim();

  // 1. Direct exact match by raw cropCode
  if (rawCode && CROP_ICON_MAP[rawCode]) return CROP_ICON_MAP[rawCode];

  const normCode = normalizeCropText(rawCode);
  const normName = normalizeCropText(rawName);

  // 2. Exact match on normalized code or name
  if (normCode && CROP_ICON_MAP[normCode]) return CROP_ICON_MAP[normCode];
  if (normName && CROP_ICON_MAP[normName]) return CROP_ICON_MAP[normName];

  // 3. Keyword matching
  const combined = `${normCode}_${normName}`;

  // Priority: Xà lách/Salad, Bắp (không phải bắp cải), Cà chua -> default cây lúa (FALLBACK)
  if (
    combined.includes("XA_LACH") ||
    combined.includes("SA_LACH") ||
    combined.includes("SALAD") ||
    combined.includes("LETTUCE") ||
    combined.includes("CA_CHUA") ||
    combined.includes("TOMATO") ||
    ((combined.includes("BAP") || combined.includes("NGO") || combined.includes("CORN")) && !combined.includes("BAP_CAI"))
  ) {
    return FALLBACK;
  }

  // Bắp cải -> bap-cai.png
  if (combined.includes("BAP_CAI") || combined.includes("CABBAGE")) {
    return "/assets/images/plant-icons/bap-cai.png";
  }

  // Đậu / Đậu phộng / Đậu phông -> dau.png
  if (
    combined.includes("DAU_PHONG") ||
    combined.includes("AU_PHONG") ||
    combined.includes("PEANUT") ||
    combined.includes("LAC") ||
    (combined.includes("DAU") && !combined.includes("DAU_TAY") && !combined.includes("DAU_HAU"))
  ) {
    return "/assets/images/plant-icons/dau.png";
  }

  // Cải xanh -> rau-an-la.png
  if (combined.includes("CAI_XANH")) {
    return "/assets/images/plant-icons/rau-an-la.png";
  }

  // Nhãn -> nhan.png
  if (combined.includes("NHAN") || combined.includes("LONGAN")) {
    return "/assets/images/plant-icons/nhan.png";
  }

  // Tiêu / Hồ tiêu -> ho-tieu.png
  if (combined.includes("TIEU") || combined.includes("HO_TIEU") || combined.includes("PEPPER")) {
    return "/assets/images/plant-icons/ho-tieu.png";
  }

  if (combined.includes("NHO") || combined.includes("GRAPE")) {
    return "/assets/images/plant-icons/nho.png";
  }

  if (combined.includes("QUYT") || combined.includes("MANDARIN")) {
    return "/assets/images/plant-icons/quyt.png";
  }

  if (combined.includes("LE") || combined.includes("PEAR")) {
    return "/assets/images/plant-icons/le.png";
  }

  // 4. Fuzzy fallback search in map
  for (const [key, path] of Object.entries(CROP_ICON_MAP)) {
    if (
      (normCode && (normCode.includes(key) || key.includes(normCode))) ||
      (normName && (normName.includes(key) || key.includes(normName)))
    ) {
      return path;
    }
  }

  return FALLBACK;
}
